### ISSUE TITLE
Licensing problem...

### ISSUE THREAD

**Issue by sebras** [svn2github/DocumentViewer#1]
This project repository has a copy of libvudroid.so which contains MuPDF licensed under the GNU GPLv3 (that is the license of both MuPDF and [VuDroid](https://code.google.com/archive/p/vudroid/) itself). I cannot find the source code to this library, nor a link pointing to exactly what version of the code was used to compile this binary. Do you mind providing the exact source code used? If you cannot then you are not really adhering to the GNU GPLv3 and so I'd need to politely ask you to remove this repository. If you need further assistance in what to do or whom to contact, you can also ask about this on the #mupdf IRC channel on freenode.net.

**Comment by svn2github** [comment]
Note this is only a mirror of a SVN repository where the underlying problem was. I checked the original repo is no longer accessible, so I'm going to delete this mirror.
